version: "3"

services:
  mqtt:
    image: emqx/emqx:5.5.0
    ports:
      - 1883:1883 # Default Port
      - 8083:8083 
      - 8883:8883 # TLS Port
      - 8084:8084 
      - 18083:18083 # http dashboard
    environment:
      - "EMQX_NAME=emqx"
      # - "EMQX_HOST=node1.emqx.io"
      # - "EMQX_CLUSTER__DISCOVERY_STRATEGY=static"
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx", "ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5
    volumes:
      - ./emqx/data:/opt/emqx/data # Data
      - ./emqx/log:/opt/emqx/log # Logs
      # - ./emqx/etc:/opt/emqx/etc:ro # Config
